config:
  partial_parse: true
  use_colors: true
  printer_width: 80
  send_anonymous_usage_stats: false

astrafy:
  target: sbx
  outputs:
    local:
      type: duckdb
      path: 'db.duckdb'
      schema: main
    sbx:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      execution_project: "{{ env_var('GCP_PROJECT') }}"
      schema: na
      threads: 8
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
#      impersonate_service_account: sa-dbt-demo@dbt-demo-aaa.iam.gserviceaccount.com

    prd:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      execution_project: "{{ env_var('GCP_PROJECT') }}"
      schema: na
      threads: 8
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
#      impersonate_service_account: sa-dbt-demo@dbt-demo-aaa.iam.gserviceaccount.com