config:
  partial_parse: true
  use_colors: true
  printer_width: 80
  send_anonymous_usage_stats: false

jaffle:
  target: sbx
  outputs:
    sbx:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      execution_project: "{{ env_var('GCP_PROJECT') }}"
      schema: na
      threads: 8
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
#      impersonate_service_account: sa-dbt-demo@dbt-demo-aaa.iam.gserviceaccount.com

    prd:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      execution_project: "{{ env_var('GCP_PROJECT') }}"
      schema: na
      threads: 8
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
#      impersonate_service_account: sa-dbt-demo@dbt-demo-aaa.iam.gserviceaccount.com

elementary:
  outputs:
    default:
      type: bigquery

      ## Service account auth, other options require other configs ##
      method: oauth

      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: bqdts_sbx_demo_dbt_elementary
      threads: 8
      location: EU
      priority: interactive