variables:
  # If your terraform files are in a subdirectory, set TF_ROOT accordingly
  TF_ROOT: . # Update this!

stages:
  - infracost

infracost:
  stage: infracost
  image:
    # Always use the latest 0.10.x version to pick up bug fixes and new resources.
    # See https://www.infracost.io/docs/integrations/cicd/#docker-images for other options
    name: infracost/infracost:ci-0.10
    entrypoint: ["terraform"]
  script:
    # If you use private modules, add an environment variable or secret
    # called GIT_SSH_KEY with your private key, so Infracost can access
    # private repositories (similar to how Terraform/Terragrunt does).
    # - mkdir -p ~/.ssh
    # - eval `ssh-agent -s`
    # - echo "$GIT_SSH_KEY" | tr -d '\r' | ssh-add -
    # Update this to github.com, gitlab.com, bitbucket.org, ssh.dev.azure.com or your source control server's domain
    # - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    # Clone the base branch of the pull request (e.g. main/master) into a temp directory.
    - git clone $CI_REPOSITORY_URL --branch=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --single-branch /tmp/base

    # Generate an Infracost cost snapshot from the comparison branch, so that Infracost can compare the cost difference.
    - |
      infracost breakdown --path=/tmp/base/${TF_ROOT} \
                          --format=json \
                          --out-file=infracost-base.json

    # Generate an Infracost diff and save it to a JSON file.
    - |
      infracost diff --path=${TF_ROOT} \
                     --compare-to=infracost-base.json \
                     --format=json \
                     --out-file=infracost.json

    # Posts a comment to the PR using the 'update' behavior.
    # This creates a single comment and updates it. The "quietest" option.
    # The other valid behaviors are:
    #   update - Create a single comment and update it. The "quietest" option.
    #   delete-and-new - Delete previous comments and create a new one.
    #   new - Create a new cost estimate comment on every push.
    # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
    - |
      infracost comment gitlab --path=infracost.json \
                               --repo=$CI_PROJECT_PATH \
                               --merge-request=$CI_MERGE_REQUEST_IID \
                               --gitlab-server-url=$CI_SERVER_URL \
                               --gitlab-token=$GITLAB_TOKEN \
                               --behavior=update
  variables:
    INFRACOST_API_KEY: $INFRACOST_API_KEY
    GITLAB_TOKEN: $GITLAB_TOKEN # With `api` scope to post merge request comments
    # If you're using Terraform Cloud/Enterprise and have variables stored on there you can specify the following to automatically retrieve the variables:
    # INFRACOST_TERRAFORM_CLOUD_TOKEN: $INFRACOST_TERRAFORM_CLOUD_TOKEN
    # INFRACOST_TERRAFORM_CLOUD_HOST: app.terraform.io
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
