# Nams your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "jaffle_common"
version: "1.1.1"

# This setting configures which "profile" dbt uses for this project.
profile: "jaffle"

require-dbt-version: [ ">=1.0.0", "<2.0.0"]

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"
