version: 2

seeds:
  - name: raw_customers
    description: A table containing id, first name and last name for dummy customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null